server:
  port: 8787

spring:
  application:
    name: Studio-Rental-Equipment
  datasource:
    driver-class-name: org.postgresql.Driver
    url: <url>
    password: <password>
    username: <username>
    hikari:
      maximumPoolSize: 10
    jpa:
      hibernate:
        naming:
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
          implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        ddl-auto: update
        show-sql: true
        database: postgresql
        database-platform: org.hibernate.dialect.PostgreSQLDialect

flyway:
  url: <url>
  user: <password>
  password: <username>